version: "3"
services:
  postgres:
    image: library/postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -h localhost -p 5432"]
      interval: 5s
      timeout: 10s
      retries: 5

  tickets-service:
    build: ./tickets-service
    image: tickets-service:latest
    container_name: tickets-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      APP_NAME: "Tickets Service"
      APP_ENV: "local"
      APP_DEBUG: "true"
      APP_URL: "http://localhost:8080"
      APP_TIMEZONE: "UTC"
      LOG_CHANNEL: "stderr"
      DB_CONNECTION: "pgsql"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_DATABASE: "tickets"
      DB_USERNAME: "program"
      DB_PASSWORD: "test"
      CACHE_DRIVER: null
      QUEUE_CONNECTION: "sync"

  films-service:
    build: ./films-service
    image: films-service:latest
    container_name: films-service
    ports:
      - "8070:8070"
    depends_on:
      - postgres
    environment:
      APP_NAME: "Films Service"
      APP_ENV: "local"
      APP_DEBUG: "true"
      APP_URL: "http://localhost:8070"
      APP_TIMEZONE: "UTC"
      LOG_CHANNEL: "stderr"
      DB_CONNECTION: "pgsql"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_DATABASE: "films"
      DB_USERNAME: "program"
      DB_PASSWORD: "test"
      CACHE_DRIVER: null
      QUEUE_CONNECTION: "sync"

  cinema-service:
    build: ./cinema-service
    image: cinema-service:latest
    container_name: cinema-service
    ports:
      - "8060:8060"
    depends_on:
      - postgres
    environment:
      APP_NAME: "Cinema Service"
      APP_ENV: "local"
      APP_DEBUG: "true"
      APP_URL: "http://localhost:8060"
      APP_URL_FILM_SERVICE: "http://films-service:8070"
      APP_TIMEZONE: "UTC"
      LOG_CHANNEL: "stderr"
      DB_CONNECTION: "pgsql"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_DATABASE: "cinema"
      DB_USERNAME: "program"
      DB_PASSWORD: "test"
      CACHE_DRIVER: null
      QUEUE_CONNECTION: "sync"

volumes:
  db-data: